### ISSUE TITLE
Can I prevent or modify the color change of the non-marker text?

### ISSUE THREAD

**Issue by MatrixManAtYrService** [IngoMeyer441/zsh-easy-motion#1]
First of all, thanks for making this.  I tend to write very long, multi-line commands in zsh, and navigating them via easy-motion like I do in vim has been really great.

I use solarized-light terminal colors for some projects, and solarized-dark for others.  The red marker text works nicely for both, but the darker non-marker text makes the text hard to see when I'm using the dark theme.  These two videos show the issue clearly:

https://asciinema.org/a/CY86N3qjqzM4S0dvXMyqglUXU?theme=solarized-light
https://asciinema.org/a/CY86N3qjqzM4S0dvXMyqglUXU?theme=solarized-dark

The colors change in vim too, but not unbearably so:
https://asciinema.org/a/D6cHS6ITHMWrVxam7TXGjfRdU?theme=solarized-dark

Can I either control which colors are used, or just disable the non-marker color change altogether?

**Comment by IngoMeyer441** [comment]
Hey, thanks for using my plug-in. :smiley: 
I can add an option to configure the colors, no problem.

**Comment by IngoMeyer441** [comment]
The latest update adds two environment variables to configure the colors with these default values (commit 74876446673a3abbd94e77ef40c56c2a4fe0e282):
```bash
EASY_MOTION_DIM="fg=8,bold"
EASY_MOTION_HIGHLIGHT="fg=196,bold"
```
You can set the `_DIM` color to a value between 232 and 255 to try different shades of grey. Visit http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html for a color reference.
I hope you can now enjoy my plugin. :blush:

**Comment by MatrixManAtYrService** [comment]
It took me a while to get back to this and check it out, but it feels right, now.  Thanks!

I settled on:

EASY_MOTION_DIM:
  - solarized dark: `fg=60,bold`
  - solarized light: `fg=180,bold`

...and left EASY_MOTION_HIGHLIGHT alone.
