### ISSUE TITLE
Two-letter jumps at line end result in incorrect line wrapping

### ISSUE THREAD

**Issue by butwerenotthereyet** [IngoMeyer441/zsh-easy-motion#2]
When there are enough matches for a jump target that two letter destinations are used, when those destinations are at line end, replacing the target line-ending character and the following character with the two letter jump destination means replacing the target character and the following newline character.  The result is that line breaks are lost:

![Screen Shot 2021-01-09 at 3 27 41 PM](https://user-images.githubusercontent.com/58348703/104110855-8f6d3800-5290-11eb-9211-2694add8d053.png)
![Screen Shot 2021-01-09 at 3 27 56 PM](https://user-images.githubusercontent.com/58348703/104110859-9300bf00-5290-11eb-950b-5f1e2d4bd131.png)

**Comment by IngoMeyer441** [comment]
Thanks for the hint. The key preview replaces the newline character and causes this visual glitch. Will fix this soon!

**Comment by IngoMeyer441** [comment]
Fixed in dfffb1241a38fee2e0c42d39dc52ba6bbe5d8d57. Could you please update the plugin and run a test?

**Comment by butwerenotthereyet** [comment]
Looking good!  The incorrect wrapping (resulting from replacing the `\n` charcters) no longer occurs.  Thank you!

That said, the coloring isn't quite right now.  It looks like the range that gets colored isn't updated to account for the fact that the string has grown longer.  See, in the last line, the last few characters (specifically the final `eiusmod tempo`) of the screenshot here:

![Screen Shot 2021-01-11 at 7 52 57 PM](https://user-images.githubusercontent.com/58348703/104267636-de5cce00-5446-11eb-958d-02b0ef8f29bf.png)

You can see that the number of new characters that were added affects the coloring here where none of the final `elit, sed do eiusmod tempo` are colored:

![Screen Shot 2021-01-11 at 7 55 28 PM](https://user-images.githubusercontent.com/58348703/104267754-1ebc4c00-5447-11eb-8090-47273a06507b.png)

**Comment by IngoMeyer441** [comment]
Ah yes, the dimmed text area needs to be expaneded. Also the cursor position needs an update. Should be fixed in the latest master. Could you run another update?

**Comment by butwerenotthereyet** [comment]
Everything seems to be working well.  Thank you very much!

![Screen Shot 2021-01-12 at 7 26 34 AM](https://user-images.githubusercontent.com/58348703/104334950-cd907480-54a7-11eb-8afc-550e30fee066.png)

**Comment by IngoMeyer441** [comment]
Thanks for testing!
