### ISSUE TITLE
zsh-easy-motion has confict with oh-my-zsh vi-mode

### ISSUE THREAD

**Issue by lyjdwh** [IngoMeyer441/zsh-easy-motion#3]
When I use zsh-easy-motion after oh-my-zsh vi-mode，I get `No such widget .zsh-system-clipboard-vicmd-vi-delete` `No such widget .zsh-system-clipboard-vicmd-vi-yank` `No such widget .zsh-system-clipboard-vicmd-vi-change`

But when I use zsh-easy-motion before oh-my-zsh vi-mode, the error disappear.

**Comment by lyjdwh** [comment]
```
plugins=(vi-mode)
source $ZSH/oh-my-zsh.sh
source $ZSH/plugins/antigen.zsh
antigen bundle IngoMeyer441/zsh-easy-motion
antigen apply
```

**Comment by lyjdwh** [comment]
When I change to zplug, the problem disappear!

**Comment by IngoMeyer441** [comment]
Anyway, thanks for reporting!
